// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Get company info",
  description: "Returns overview information about MEP Erictric Technology Ltd \u2014 a Rwanda-based MEP (mechanical, electrical, plumbing) and elevator contractor.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "MEP Erictric Technology Ltd",
      country: "Rwanda",
      website: "https://meperictrictech.com",
      focus: "MEP (mechanical, electrical, plumbing) contracting, elevator supply & installation, fire safety, CCTV & security, and building maintenance.",
      projects_completed: "26+",
      years_experience: "10+",
      clients: "100+ satisfied clients",
      government_institutions_served: [
        "MININTER",
        "MINAFFET Procurement Office",
        "NISR"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "Lists the MEP and building technology services offered by MEP Erictric Technology Ltd.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = [
      { name: "Elevator supply & installation", detail: "Passenger and freight elevators for residential, commercial, hospital, and government buildings." },
      { name: "Electrical installation", detail: "Building electrical works, switchgear, transformers, MV/LV cabling, and generators." },
      { name: "Fire safety systems", detail: "Fire alarm and firefighting system design and installation." },
      { name: "CCTV & security", detail: "CCTV cameras, access control, and IP telephony networks." },
      { name: "Plumbing", detail: "Building plumbing and water systems." },
      { name: "Transmission & street lighting", detail: "Power transmission line and public lighting projects." },
      { name: "Maintenance", detail: "Ongoing maintenance of MEP and elevator systems." }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Returns contact details (website, WhatsApp, MEP calculator) for MEP Erictric Technology Ltd.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      website: "https://meperictrictech.com",
      contact_page: "https://meperictrictech.com/contact",
      mep_calculator: "https://mepestimatecalculator.vercel.app/",
      company_profile: "https://drive.google.com/file/d/1rSXmarbXMECfryBugomxR1DQU3jkHUec/view?usp=drive_link"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mep-erictric-mcp",
  title: "MEP Erictric Technology",
  version: "0.1.0",
  instructions: "Public information tools for MEP Erictric Technology Ltd \u2014 a Rwanda-based MEP and elevator contractor. Use get_company_info for an overview, list_services for the services catalog, and get_contact_info for website and contact links.",
  tools: [get_company_info_default, list_services_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
